surface selection from detected surfaces added
wrld3d/wrld-unity-ar-samples pull request #5
Opened 2020-11-13 06:45 UTC by Tanveerbutt

Surface selection from detected surfaces added
User scan for surfaces and then select one of the surface if there are multiple.
Map will be shown on selected surface.

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Materials/Plane Materials/Border Line.mat
> +%YAML 1.1
We don't need this material as we can change this via line renderer

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Scripts/WRLDARMapController.cs
> +    [SerializeField] private GameObject[] m_SurfaceStateMsg;
Should only field of text and change text only.

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Scripts/WRLDARMapController.cs
> +    private ARRaycastManager m_RaycastManager;
Naming convention

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Scripts/WRLDARMapController.cs
> +    private bool m_isSurfaceDetected = false;
These can be removed

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Scripts/WRLDARMapController.cs
> +            if (Input.touchCount > 0)
indentation

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Scripts/WRLDARMapController.cs
> +                        DisableDetectedPlaneVisuals(plane.trackableId);
break loop here

2020-11-13 07:16 UTC, Tanveerbutt commented on Assets/WRLD SDK Samples/Scripts/WRLDARMapController.cs
> +        m_arPlaneManager.planePrefab.GetComponent<LineRenderer>().enabled = false;
Move repeated code into method

2020-11-13 07:23 UTC, ArslanJafri requested changes
Changes needed as discussed on call and added in comments by @Tanveerbutt

2020-12-04 06:49 UTC, ArslanJafri approved these changes

2020-12-04 06:49 UTC, merged